### ISSUE TITLE
CSW outputSchema="own" not using expected style sheets

### ISSUE THREAD

**Issue by asedgmen** [geonetwork-ga/core-geonetwork#23]
When making a CSW request with the outputSchema value set to "own", one of own-brief.xsl, own-summary.xsl or own-full.xsl in WEB-INF/data/config/schema_plugins/iso19115-3/present/csw should be applied to the response documents.  Testing has shown that the equivalent iso-*.xsl style sheets in the same directory are being applied instead.

**Comment by sppigot** [comment]
Fixed in commit ee2ed983d815e29d7c42f86619819f2933cd379f

Also: added support for presentation XSLTs corresponding to csw virtual service name. If required xslt is in {schema}/present/csw.externalrecords (ie. name of virtual csw service) then it will be used, otherwise default {schema}/present/csw XSLT will be used. See commit 5015aa1663fed46f88d9f33a057eb58939652d23
